services:
  jetson-app:
    build: .
    image: jetson-python310-min

    runtime: nvidia

    volumes:
      - ./:/workspace
      - venv:/opt/venv

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility

    ipc: host
    shm_size: "1gb"

    command: >
      bash -lc "
        python -V &&
        ffmpeg -version | head -n 1 &&
        python main.py
      "

volumes:
  venv:
