services:
  obs_vps_app_v2:
    build: .
    image: obs-inference-jetson:tensorrt-arm64

    runtime: nvidia

    volumes:
      - ./:/workspace
      - venv:/opt/venv
      - ./assets/compressed_models:/app/models/


    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - VENV_PATH=/opt/venv
      - PIP_INDEX_URL=https://pypi.org/simple
      - MALLOC_CHECK=0 
      - OPENBLAS_CORETYPE=ARMV8
      - LD_PRELOAD=

    ipc: host
    shm_size: "1gb"

    command: >
      bash -lc "
        set -e;
        cd /workspace; 
        python3 -V;

        if [ -f setup.py ]; then
          echo 'Setting up OBS package...';
          python3 -m pip install -e . --no-deps;
        fi;
        if [ -f requirements.txt ]; then 
          python3 -m pip install -r requirements.txt --no-deps; 
          python3 -m pip install --upgrade pyparsing --no-deps; 
          python3 -m pip uninstall pynvml;
          python3 -m pip install nvidia-ml-py --no-deps; 
        fi; 

        python3 scripts/obs_pipeline.py --model_name=assets/compressed_models/mixed_dataset_trained_yolov8s_fixed_mixed_batch_trt_fp16_noibt8.engine --video_source=samples/sample_video.mp4 --use_TRT --only_FPS --roi;
      "

volumes:
  venv:

